language: node_js
node_js:
- '6'
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY
  bucket: ryandens.com
env:
  global:
    secure: dVCXr0YEgG4hLDfnHKg+a8Br3o3HbTzqYbrtvRMCvhCDwbX1PHJRMVrT1qz32dxpAvbUhdviqEF/1z4+jR57xDfV3FmtuY1U/EmTeYxNleNN1a2MTBxrR94fs2+ODO/Y8UeBLslBwyMujRIhkqiJFhdOob3Xx4KVlfhVew1vSJLuaoYYdROBymlkRjkAkYEymTB1M63DJzzGyNeEvJ+w8ObZT/tp658jGonVbWvrfHAShHt9tnhyBtDkh4euuIoDf42Ym6uj1MFcE269/T6HruiGxfZ0UorzkIQBKjuPxaiYAZaiKy0ettv2R2iMzjLuWGoPYgIX4vFWT+lBzxmNd0ynwx74sJCiXPxIDy2SI0BqRFzJTTOs1kBsWZTzh6ibvrwGX5SStzKpwfaMTfD3mLo9tllKSlx7BU2wfjssqgf145YpLoUMni66bVMJYTOtpOwVm9S/S43Oo+nDoRLh0qM3+SZ4A2quezsvlCfEovigPJ2hW3N5TBwRKo49+9jto/E1sevlgVPVAfl2rRALgb1tFog6Uyp6icIVHhYAVAZvA7jSkKPP5kjIYh7HYHB4DPCXGMGM2BzQ69cyw93RFx6efFznpyE8PJA82P4qvfWyoq6xVsCeRoRfusjNWnM4DPKM5/eIjAXsjsPvkco+yaoEGmtQ+nc0wuJ03csOmxk=
