language: node_js
node_js:
- '6'
deploy:
  provider: s3
  access_key_id: AWS_ACCESS_KEY
  secret_access_key: AWS_SECRET_KEY
  bucket: ryandens.com
env:
  global:
  - secure: Pofu9tCMDaPaIQMIcBez9AFfnr3TC4v/SkqD6YtoihvjRgc/aHaB1JX66H1VksQv/prHYmzgOf7OM6EZt1yE/abKo6H5a2W9uSi1GUK3kekbx/yPBl07Z2kRMger/mdqK+ujJNwZZ0wcbtWvWiAwRSMcY5hnwllezqY1knNEfz0Nht2VftasR/roS0T2x0G6rbw22d/yLI5bg4jA/s2L0dCXjjX41uXnsDdmy2LQWZYnt85H8fcjiqGeb4arM5eVoMfXTy7J799pvuHB3c84yXkXvAo7Ia5cCQWSAhzA05ayXFKSxVlvFQwFd1QNN8hemOz//BEA5h6vgT4e0Gu+ZuI+238nSdkTXPGKhCQXI2hWz8pTYij/VZ7kGyw5YoaImf6nzQYheQOD7JYGiHU2ryA/NNF1ISg+mXGX4e9tPimqG6D3RotMRvxzZQ7ZEantss0OThxBLkJmhWmZR0U3ZjuMmjfeASMoysW5mbCwE7EG4kW2OB8p/onhYjy6spOItrTaeZ+qzuaFXGoYBQ60AocMujSgR0jKDLZNJLSSyhM3oLuna0XAQnNUMSddhn3kxPT8w0GLMbR8riVsyj6QZrXH8GoijZRt06bCbfiD/31vER48de6PwdfId2JvlpPNE1duhP8u3me+JGi1rvODaQQyBwLRiZTsbS5/1wUekI8=
  - secure: hcI0R2bsWZFcuLCrbV6hg45NjI9tMor9AzwjL5G9kc6eE4SGdAe/F7j4mtZg/qZ9wdSoOs+24oZbK4j5cEOtV1+TIdNShpHnDFEk4As6KSMOT11iM2Ktc3/K+JplzI8e/YXK6gFSK1vwjA4y5TRJ6r4UnoIGh/jPLE/XyNJI5rsgaXjJL6FDzJDilkib8/3aPDv2VQzPbh2GS/y3jNk+uPHn3sCTAC32h8gCm4P48YCrW+8qwXEcWYup5QD4oBUXWctrg5TPTEev9mbVcUOq/TNJOzYFn9Tbi5HxQ/rI6lMuBHw7BA4d6gRouoyaETlLBnaVwoPGOOotewmcamrNWFmQdalCXVyTEv2tK+mOC/6YJFUZgndLyhilGtqCinhLOY3M8YG6LGtMb3yKwzTTGSlMgUWH9fFF/aelArmL7tG5YVdkhlCuGxuXE90YoCE5EIizgUfDYvm33+/wtPRq+rMITqSnieXlsO11xMF4kmKLMk90j8OqZq8403Ku/6h4AePYcxCCwZyftMpPUpqi0sS0udABcdQ/tudSdL9h/22zmlfttgpierSeYND2b+wZDCG/ns7pQTFJTJsFUi+SDnX5TwAy+t55kgJ7qXEMpuQXxbZNkgkysRuvw0XL4O6zSa5Arc8K6VJZF7TsRNd9UXGnRVbyRFxqVIiLY3RYZi8=
